Fixed wrong metal addition result
Gobot1234/steam.py pull request #268
Opened 2023-07-19 19:20 UTC by nikviktorovich

## Summary

This PR prevents a case when `tf2.Metal(1.88) + tf2.Metal(1.11) != tf2.Metal(3)` and adds some more test cases to assure it. It also enforces `Metal.__add__` method to return an instance of a `Metal` instead of a `Fracture` to make addition chains of more than 2 elements stable (due to rounding and returning an instance of `Fracture`, the required precision could be lost after multiple additions). The breaking change here though is adding anything other than `tf2.Metal` to `tf2.Metal` may result in an error (except a `Fracture` with denominator 9, but it will result in typing error anyway, cause `Fracture` is not a `Metal`).

## Checklist

- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-07-19 20:43 UTC, Gobot1234 requested changes
I agree there are a few issues here I just don't entirely agree with how you've gone about fixing them and there are definitely some floating point rounding issues which I think are better handled in init and the math by the super class's implementation of these methods

2023-07-19 20:43 UTC, Gobot1234 commented on steam/ext/tf2/currency.py
> +        return Metal(value)
```suggestion
        return Metal(super().__add__(other))
```

2023-07-19 20:45 UTC, Gobot1234 commented
FWIW I've changed the methods to
```py
    def __new__(cls, value: SupportsMetal, /, *, _normalize: bool = ...) -> Self:
        value = float(value)

        self = object.__new__(cls)

        try:
            true_value = round(value, 2)
        except (ValueError, TypeError):
            raise TypeError("non-int passed to Metal.__new__, that could not be cast") from None

        if not math.isclose(value, true_value):
            raise ValueError("metal value's last digits must be close to 0")

        stred = f"{true_value:.2f}"
        if stred[-1] != stred[-2]:
            raise ValueError("metal value must be a multiple of 0.11")

        fractional, integer = math.modf(true_value)
        self._numerator = int(integer) * 9 + math.floor(fractional * 10)  # I think this is more reliable at extracting the parts here
        return self

	...

    def __str__(self) -> str:
        return f"{math.floor(self._numerator * 100 / 9) / 100:.2f}"  # str(Metal(1.88)) was 1.89 before whoops
```

2023-07-19 21:23 UTC, nikviktorovich commented
The problem with your solution is that the result of extracting true value this way
```
fraction = Fraction(<more than 5>, 9)
value = float(fraction)
true_value = round(value, 2)
```
fails both
```
if not math.isclose(value, true_value):
    ...
```
and
```
stred = f"{true_value:.2f}"
if stred[-1] != stred[-2]:
    ...
```
validations in the constructor. But I see the point. I'll try to come up with a different solution, thanks.

2023-07-19 22:13 UTC, Gobot1234 commented
How does this look? https://gist.github.com/Gobot1234/925ecdaf2d911ccc207f0c77ab62d8b9

2023-07-19 22:20 UTC, Gobot1234 commented
My issues with actually implementing `__add__` are 1 there are a lot of cases to handle e.g. Fraction() + float() works according to the original implementing, 2 we need to then implement all the other magic methods which is a lot of work, 3 this implementation is actually incompatible with the superclass.

At the end of the day returning a Fraction IMO is fine, it will have all the correct behaviour apart from formatting and if you want that just cast it to Metal.

2023-07-20 06:49 UTC, nikviktorovich commented
> How does this look? https://gist.github.com/Gobot1234/925ecdaf2d911ccc207f0c77ab62d8b9 (ignoring the lack of `__add__` overloading) this should allow for infinite precision addition and fix the error where `Metal(1.88) + Metal(1.22) != Metal(3)`

It seems like this way of validation works like a charm!

> 1. there are a lot of cases to handle e.g. `Fraction() + float()` works according to the original implementation but not here

I'm not sure if this should even be allowed. In my opinion, `tf2.Metal(0.11) + tf2.Metal(0.22)` looks much more readable than either `tf2.Metal(0.11) + 0.22` or `tf2.Metal(0.11) + Fraction(2, 9)`. But if you wanna stick with this behavior, there's not really much of a work to implement the magic methods (considering, only addition, subtraction, multiplication and division are allowed):

```python
class Metal(Fraction):
    __slots__ = ()

    @overload
    def __new__(cls, value: SupportsMetal, /) -> Self:  # type: ignore
        ...

    def __new__(cls, value: SupportsMetal, /, *, _normalize: bool = ...) -> Self:
        scrap = cls.extract_scrap(value)
        return super().__new__(cls, scrap, 9)
    
    @classmethod
    def extract_scrap(cls, value: SupportsMetal) -> int:
        if isinstance(value, Fraction):
            if value.denominator in {9, 3, 1}:
                return value.numerator * (9 // value.denominator)
            raise ValueError("cannot convert Fraction to Metal, denominator isn't 1, 3 or 9")

        try:
            value = Decimal(value)
        except (ValueError, TypeError):
            raise TypeError("non-int passed to Metal.__new__, that could not be cast") from None

        fractional, integer = modf(value)
        if not math.isclose(fractional - round(fractional, 2), 0, abs_tol=1e-9):
            raise ValueError("metal value's last digits must be close to 0")

        digits = round(fractional, 2).as_tuple().digits
        if len(digits) >= 2 and digits[0] != digits[1]:
            raise ValueError("metal value must be a multiple of 0.11")
        
        return int(integer) * 9 + digits[0]
    
    def __add__(self, other: SupportsMetal) -> Fraction:
        scrap = Metal.extract_scrap(other)
        return Fraction(self.numerator + scrap, 9)
    
    def __sub__(self, other: SupportsMetal) -> Fraction:
        scrap = Metal.extract_scrap(other)
        return Fraction(self.numerator - scrap, 9)
    
    def __mul__(self, other: SupportsMetal) -> Fraction:
        scrap = Metal.extract_scrap(other)
        return Fraction(self.numerator * scrap, 9)
    
    def __div__(self, other: SupportsMetal) -> Fraction:
        scrap = Metal.extract_scrap(other)

        if self.numerator % scrap != 0:
            raise ValueError(f'{self.numerator} scrap cannot be divided by {scrap}')
        
        return Fraction(scrap, 9)

    def __str__(self) -> str:
        return f"{self.numerator // self.denominator}.{f'{(self.numerator % self.denominator) * 9 // self.denominator}' * 2}"

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}({str(self)!r})"
```

What do you think about this implementation?

2023-07-20 09:23 UTC, Gobot1234 commented
LGMT thanks

2023-07-20 09:49 UTC, nikviktorovich commented
Okay then, I changed the PR commit. Thanks.

2023-07-20 10:55 UTC, Gobot1234 commented
@nikviktorovich how does this all look now?

2023-07-20 11:04 UTC, nikviktorovich commented
Tests look good and pass successfully, so it looks like the issue is resolved. Great work!

2023-07-20 11:05 UTC, merged